language: 
    - python
python:
    - "2.7"

before_install:
    - sudo apt-get install python-software-properties -y
    - echo "yes" | sudo apt-add-repository ppa:ubuntugis/ppa
    - sudo apt-get update -y
    - sudo apt-get install geos -y
    - sudo apt-get install openjdk-7-jre-headless -y
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.0.deb
    - sudo dpkg -i elasticsearch-0.90.0.deb
    - sudo service elasticsearch start
    - sudo gem install bundler --no-ri --no-rdoc
    - createuser -d -s whwn
    - createdb -Uwhwn -E utf8 whwn

install:
    - export DJANGO_SETTINGS_MODULE=settings.development
    - bundle install
    - pip install -r requirements.txt

script:
    - python app/manage.py test
      
